### ISSUE TITLE
Add .gitignore file

### ISSUE THREAD

**Issue by michalirak** [yashasvi-goel/Algorithms-Open-Source#35]
Repo currently includes:
- C++ build files (such as object file [here](https://github.com/yashasvi-goel/Algorithms-Open-Source/blob/master/CircleDrawing/C%2B%2B/Bresenham/circle.o))
- pyc file [here](https://github.com/yashasvi-goel/Algorithms-Open-Source/tree/master/PageRank/Python/__pycache__) (\_\_pycache\_\_ directory is also not needed)

**Comment by yashasvi-goel** [comment]
@NicholasACTran @rhythm1705

**Comment by NicholasACTran** [comment]
I'm not familiar enough with C++ build files or pyc files, so I will have to pass on this

**Comment by aaakashkumar** [comment]
Added a `.gitignore` to prevent unnecessary files from getting uploaded. It excludes unnecessary files from C, C++, C# and Python builds, as well as files from related IDEs. Please merge #38.

**Comment by michalirak** [comment]
Note that since the .gitignore was created after related files were uploaded to the repo, you will also need to delete the existing files (.pyc and so on)

**Comment by yashasvi-goel** [comment]
PR #38 merged and existing object files deleted. If any are left do raise an issue.
