### ISSUE TITLE
Restructure repo to be more uniform

### ISSUE THREAD

**Issue by michalirak** [yashasvi-goel/Algorithms-Open-Source#40]
Current structure is Algorithm Category -> Algorithm Type -> Language -> Implementation (can be various algorithms)

I propose Algorithm Category -> Algorithm -> Language -> Implementation for only one algorithm.
This will allow:
- Easier documentation in project's README
- Easier search for algorithms since you will not need to go through all of the languages to find a given algorithm
- Less confusion and arbitrariness in sorting the repo and sorting through it.

@yashasvi-goel  I can work on this myself if you assign it to me.

**Comment by michalirak** [comment]
Not sure if I should add this to this issue or a new one, but the repo should also be fairly standardized with regard to file names.

**Comment by michalirak** [comment]
See PR #56

**Comment by NicholasACTran** [comment]
@yashasvi-goel  @michalirak We should close this issue.
